### ISSUE TITLE
Sliders have empty space to the right

### ISSUE THREAD

**Issue by ziyang-theory** [utoronto-theory/webpage#15]
### The problem
![Screen Shot 2023-05-25 at 16 27 37](https://github.com/utoronto-theory/webpage/assets/125936694/9db27c9e-c380-4e0b-9011-12001daa9f06)
It has been a long-standing issue that the sliders have no padding on the left but about 30 pixel padding on the right, which makes it asymmetric. 

### Hypothesis and potential solutions
It believe the problem is that the window has a width of 960 pixels but the image we provide only has 930 pixels, and since we have 0 padding on the left, it leaves 30 pixels white space on the right. The ideal solution is to put 15 pixels on the left and 15 pixels on the right such the images lies in the middle.

I tried to manipulate the padding for the slider but it does not work. Two other potential sub-optimal solutions are:
- use width=960 pixel images for the slides (this will be a good solution but we need to replace some of the images)
- change the window width to 930 pixel (this works but not a good solution)

So far I do not have a good solution so I will just leave an issue here and hope someone with better css knowledge is able to fix it.

**Comment by ziyang-theory** [comment]
PR #16 addresses the issue.

**Comment by sachdevasushant** [comment]
Thanks, Ziyang for fixing this issue.
